all:
  hosts:
    node1:
      ansible_host: 10.0.123.11
      ip: 10.0.123.11
      access_ip: 10.0.123.11
      ansible_user: root
    node2:
      ansible_host: 10.0.123.12
      ip: 10.0.123.12
      access_ip: 10.0.123.12
      ansible_user: root
    node3:
      ansible_host: 10.0.123.13
      ip: 10.0.123.13
      access_ip: 10.0.123.13
      ansible_user: root
    node4:
      ansible_host: 10.0.123.14
      ip: 10.0.123.14
      access_ip: 10.0.123.14
      ansible_user: root
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
